# 1. 데이터 수집
- 기본적으로 데이터를 읽고, 핸들링하는데 사용하는 패키지는 `numpy`, `pandas`입니다.
- 패키지를 등록하기 위해서는 `import 패키지명 as 간축어`를 통해서 사용합니다.

## 1.1 데이터 파일 읽기

In [2]:
# package 등록
import numpy as np
import pandas as pd

In [5]:
# 데이터 읽기
sample = pd.read_csv("sample.csv")
sample.head()

# 엑셀 파일을 읽는 방법
# pd.read_excel("filename.xlsx", sheet_name = "Sheet1", usecols = ["A", "C"])

       date  cnt  death  injured
0  19920101   38      2       47
1  19920102   41      0       49
2  19920103   57      1       62
3  19920104   52      2       57
4  19920105   53      0       65
5  19920106   58      1       75
6  19920107   55      1       59
7  19920108   37      1       37
8  19920109   72      2       83
9  19920110   73      2       95

In [6]:
# 데이터 크기 확인
sample.shape

(9497, 4)

In [8]:
# 데이터의 정보 확인
sample.info()
sample.describe()

               date          cnt        death      injured
count  9.497000e+03  9497.000000  9497.000000  9497.000000
mean   2.004566e+07    38.671475     0.792987    51.946825
std    7.500870e+04    11.284775     0.986803    14.653647
min    1.992010e+07     9.000000     0.000000    13.000000
25%    1.998070e+07    31.000000     0.000000    42.000000
50%    2.004123e+07    37.000000     1.000000    50.000000
75%    2.011070e+07    44.000000     1.000000    60.000000
max    2.017123e+07    99.000000    10.000000   141.000000

In [12]:
# 데이터 컬럼 선택
#sample
sample["date"].head()

0    19920101
1    19920102
2    19920103
3    19920104
4    19920105
Name: date, dtype: int64

In [18]:
# 원하는 데이터만 일부 추출
#sample.head()
#sample[sample['death'] != 0]
sample[sample['death'] != 0]

          date  cnt  death  injured
0     19920101   38      2       47
2     19920103   57      1       62
3     19920104   52      2       57
5     19920106   58      1       75
6     19920107   55      1       59
...        ...  ...    ...      ...
9484  20171219   29      1       33
9485  20171220   34      1       50
9491  20171226   21      1       23
9493  20171228   33      1       55
9496  20171231   21      1       27

[4900 rows x 4 columns]

In [31]:
sample.head()
sample.tail()

          date  cnt  death  injured
9492  20171227   29      0       45
9493  20171228   33      1       55
9494  20171229   29      0       37
9495  20171230   25      0       42
9496  20171231   21      1       27

In [29]:
# 원하는 데이터 행 선택
# sample[1:2]
# sample.iloc[2]

# 원하는 열 선택
# sample.iloc[:, 0:2]
# sample[['date', 'cnt']]
# sample['date']

# tail의 의미
#sample.tail()
#sample.iloc[-5:]

# 원하는 행 삭제
sample.drop(0)
sample.drop([0,1])

# 원하는 열 삭제
sample.drop('date', axis = 1)

          date  cnt  death  injured
4     19920105   53      0       65
5     19920106   58      1       75
6     19920107   55      1       59
7     19920108   37      1       37
8     19920109   72      2       83
...        ...  ...    ...      ...
9492  20171227   29      0       45
9493  20171228   33      1       55
9494  20171229   29      0       37
9495  20171230   25      0       42
9496  20171231   21      1       27

[9493 rows x 4 columns]

## 1.2. 크롤링을 이용한 데이터 수집 (BeautifulSoup이용)
- 데이터를 직접 다운로드 할 수 있겠지만, 데이터가 따로 업로드 되어있지 않은 경우, 웹 사이트에 있는 원하는 데이터를 추출하는 방법을 스크래핑 혹은 크롤링 이라고 합니다.
- `BeautifulSoup`은 파이썬에서 크롤링을 하기위해 사용하는 대표적인 라이브러리 중 하나입니다.

In [1]:
import requests
from bs4 import BeautifulSoup

# 1. 웹페이지 요청
url = "https://news.naver.com/"   # 네이버 뉴스 메인 페이지
response = requests.get(url)

# 2. HTML 파싱
soup = BeautifulSoup(response.text, features="html.parser")

# 3. 원하는 데이터 추출 (기사 제목)
# strong 태그 중 class="cnf_news_title"만 추출
titles = soup.find_all("strong", class_="cnf_news_title")

print("=== 네이버 뉴스 기사 제목 ===")
for t in titles[:10]:
    print(t.get_text(strip=True))

=== 네이버 뉴스 기사 제목 ===
[단독]UAE 투자부 차관, SK하이닉스 방문…투자 기대 ↑
"월급쟁이 맞아?" 1인당 440억 '잭팟'…현금으로 챙겨간 오픈AI 직원들
“방 2개 집에 6인 가족?”… 정부, 결국 청약통장 ‘실거주 추적’  들어갔다
조승래 "무소속 출마 김관영 영구 복당 불허 대상"
18일부터 고유가 지원금 2차 지급…누가, 얼마나, 어떻게 받나
"삼전닉스 놓쳤다고? 싸고 좋은 주식 널렸다"…고수의 조언
대구라는 도시와 김부겸이라는 사람, 그 둘의 화학작용
‘고립 출산’한 베트남인 기능실습생이 사체유기죄?
집값 잡으려다 세입자 허리 휠판?…전세가 매매보다 더 뛴다
李대통령 "동학농민혁명, 韓민주주의 첫걸음…국민이 주인인 나라 만들 것"

In [ ]:
# 1. 웹페이지 요청
url = "https://news.naver.com/"   # 네이버 뉴스 메인 페이지
response = requests.get(url)
print(response)
print(response.text)

In [ ]:
# 2. HTML 파싱
soup = BeautifulSoup(response.text, features="html.parser")
soup

In [ ]:
# 3. 원하는 데이터 추출 (기사 제목)
# strong 태그 중 class="cnf_news_title"만 추출
titles = soup.find_all("strong", class_="cnf_news_title")
print(titles[0])
print(" ")
print(" ")
print(" ")
print("=== 네이버 뉴스 기사 제목 ===")
# 10개 정도만 우선 불러오기
for t in titles[:10]:
    print(t.get_text(strip=True))